'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Archive,Camera,ChevronLeft,ChevronRight,CircleAlert,FolderOpen,ImageDown,Loader2,Pause,Play,RefreshCw,SlidersHorizontal,Square,Target,TriangleAlert} from 'lucide-react';
import {api,archiveUrl,previewUrl,WS_API} from '@/lib/api';
import type {DatasetSummary,Defect,InspectionResult,Job,LogRow,Sample,SystemInfo,StorageRuntime} from '@/types';
import {DatasetLoader} from './DatasetLoader';import {LensViewer} from './LensViewer';import {StatusMatrix} from './StatusMatrix';import {TopBar} from './TopBar';import {TrendChart} from './TrendChart';
export function InspectionDashboard(){
 const[info,setInfo]=useState<SystemInfo|null>(null),[datasets,setDatasets]=useState<DatasetSummary[]>([]),[datasetId,setDatasetId]=useState(''),[samples,setSamples]=useState<Sample[]>([]),[results,setResults]=useState<InspectionResult[]>([]),[current,setCurrent]=useState<string|null>(null),[channel,setChannel]=useState('h'),[job,setJob]=useState<Job|null>(null),[logs,setLogs]=useState<LogRow[]>([]),[loader,setLoader]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[hold,setHold]=useState(false),[bottomTab,setBottomTab]=useState<'wt'|'yield'|'messages'>('wt'),[selectedDefect,setSelectedDefect]=useState(0),[probe,setProbe]=useState<{x:number;y:number;gray:number|null}|null>(null),[storage,setStorage]=useState<StorageRuntime|null>(null),[errorMode,setErrorMode]=useState<'all'|'at'|'none'>('all');
 const refreshSystem=useCallback(()=>Promise.all([api.system().then(setInfo),api.storageState().then(setStorage)]).then(()=>{}).catch(()=>{}),[]);
 async function refreshDatasets(prefer?:string){const ds=await api.datasets();setDatasets(ds);const id=prefer||datasetId||ds[0]?.id||'';if(id){setDatasetId(id);await loadDataset(id)}}
 async function loadDataset(id:string){const[s,r]=await Promise.all([api.samples(id),api.results(id)]);setSamples(s.items);setResults(r.items);if(s.items.length){setCurrent(c=>s.items.some(x=>x.id===c)?c:s.items[0].id);const first=s.items[0];setChannel(Object.keys(first.images)[0]||'h')}}
 useEffect(()=>{refreshSystem();refreshDatasets();api.logs().then(x=>setLogs(x.items.reverse())).catch(()=>{})},[]);
 const resultMap=useMemo(()=>new Map(results.map(r=>[r.sample_id,r])),[results]),sample=useMemo(()=>samples.find(s=>s.id===current)||null,[samples,current]),currentResult=current?resultMap.get(current):undefined;
 const visibleDefects=useMemo(()=>errorMode==='none'?[]:(currentResult?.defects||[]).filter(d=>errorMode==='all'||(d.tolerance||'AT')==='AT'),[currentResult,errorMode]);
 const counts=useMemo(()=>results.reduce((a,r)=>{a[r.status]=(a[r.status]||0)+1;return a},{OK:0,NOK:0,WARN:0} as Record<string,number>),[results]),yieldPct=results.length?counts.OK/results.length*100:0;
 const wtSamples=useMemo(()=>samples.filter(s=>s.wt_index===(sample?.wt_index||1)),[samples,sample]);
 async function run(){if(!datasetId)return;setBusy(true);try{const j=await api.run(datasetId);setJob(j);const ws=new WebSocket(`${WS_API}/ws/jobs/${j.id}`);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.job)setJob(m.job);if(m.result){setResults(prev=>[...prev.filter(x=>x.sample_id!==m.result.sample_id),m.result]);if(!hold){setCurrent(m.result.sample_id);setSelectedDefect(0)}}if(['completed','failed','cancelled'].includes(m.type)){api.logs().then(x=>setLogs(x.items.reverse()));api.storageState().then(setStorage)}};ws.onerror=()=>setToast('Live WebSocket disconnected. REST results remain available.')}finally{setBusy(false)}}
 async function inspectSelected(){if(!datasetId||!sample)return;setBusy(true);try{const r=await api.inspectOne(datasetId,sample.id);setResults(p=>[...p.filter(x=>x.sample_id!==r.sample_id),r]);setSelectedDefect(0);await api.storageState().then(setStorage)}finally{setBusy(false)}}
 async function snap(){if(!datasetId||!sample)return;const r=await api.snapshot(datasetId,sample.id,channel);setToast(`Lens snapshot saved: ${r.saved}`)}
 function select(id:string){setCurrent(id);setSelectedDefect(0);const s=samples.find(x=>x.id===id);if(s&&!s.images[channel])setChannel(Object.keys(s.images)[0]||'h')}
 function relative(step:number){if(!sample||!samples.length)return;const i=samples.findIndex(x=>x.id===sample.id),next=samples[(i+step+samples.length)%samples.length];select(next.id)}
 async function toggleStorage(){const r=storage?.active?await api.storageStop():await api.storageStart();setStorage(r)}
 return <><TopBar info={info} onRefresh={refreshSystem}/><div className="commandBar"><div className="datasetChooser"><FolderOpen/><select value={datasetId} onChange={e=>{setDatasetId(e.target.value);loadDataset(e.target.value)}}>{datasets.map(d=><option value={d.id} key={d.id}>{d.name} · {d.sample_count} lenses</option>)}</select><button className="softButton" onClick={()=>setLoader(true)}>Load folder</button><button className="iconButton" onClick={()=>refreshDatasets()}><RefreshCw/></button></div><div className="heroKpis"><Kpi label="Current yield" value={`${yieldPct.toFixed(1)}%`} tone={yieldPct>=95?'good':yieldPct>=85?'warn':'bad'}/><Kpi label="Inspected" value={`${results.length}/${samples.length}`}/><Kpi label="NOK" value={String(counts.NOK)} tone="bad"/><Kpi label="Image storage" value={storage?.active?`ON · ${storage.saved_lenses}`:'OFF'} tone={storage?.active?'good':''}/></div></div>
 <div className="dashboardGrid"><StatusMatrix samples={samples} results={resultMap} current={current} onPick={select} onArchive={async wt=>{const r=await api.archiveRing(datasetId,wt);setToast(`WT ${wt} archived · ${r.images} images`)}}/><LensViewer datasetId={datasetId} sample={sample} channel={channel} defects={visibleDefects} onChannel={setChannel} labels={info?.settings.channel_labels||{h:'High Contrast',d:'Dark Field'}} hold={hold} onHold={()=>setHold(v=>!v)} selectedDefect={selectedDefect} onProbe={setProbe}/><section className="glassPanel lensInfoPanel"><div className="panelHead compact"><div><span className="eyebrowText">CURRENT LENS</span><h2>{sample?.metadata.code||sample?.base_name||'No lens selected'}</h2><p>{sample?`WT ${sample.wt_index} · Position ${sample.position}/16`:'—'}</p></div><div className="lensNav"><button onClick={()=>relative(-1)}><ChevronLeft/></button><button onClick={()=>relative(1)}><ChevronRight/></button></div></div><div className={`resultHero ${(currentResult?.status||'idle').toLowerCase()}`}><span>{currentResult?.status||'NOT EVALUATED'}</span><small>{sample?.metadata.defect_label||'Waiting for inspection'}</small></div><div className="metadataGrid"><Meta label="Category" value={sample?.category}/><Meta label="Image no." value={sample?.metadata.image_no}/><Meta label="Machine" value={sample?.metadata.machine}/><Meta label="Event" value={sample?.metadata.event_id}/><Meta label="Channel" value={info?.settings.channel_labels[channel]||channel.toUpperCase()}/><Meta label="Pixel" value={probe?`${probe.x}, ${probe.y} · gray ${probe.gray??'—'}`:'move over image'}/></div><div className="errorFilter"><span>Error display</span><div>{(['all','at','none'] as const).map(x=><button key={x} className={errorMode===x?'active':''} onClick={()=>setErrorMode(x)}>{x==='all'?'All':x==='at'?'AT only':'None'}</button>)}</div></div><div className="defectList"><div className="subHead"><h3>Detected defects</h3><span>{visibleDefects.length}</span></div>{visibleDefects.length?visibleDefects.map((d,i)=><button className={i===selectedDefect?'defectItem selected':'defectItem'} key={`${d.name}-${i}`} onClick={()=>setSelectedDefect(i)}><i className={d.severity}/><span><b>{d.name}</b><small>{(d.tolerance||'AT')} · {d.channel?.toUpperCase()||channel.toUpperCase()} · {(d.confidence*100).toFixed(1)}%</small></span><em>{d.severity}</em></button>):<div className="emptyState"><CircleAlert/>No visible defects</div>}</div><div className="lensActions"><button onClick={inspectSelected}><Target/>Evaluate</button><button onClick={snap}><Camera/>Snapshot</button><button className={storage?.active?'active':''} onClick={toggleStorage}><ImageDown/>{storage?.active?'Stop storage':'Start storage'}</button><Link href="/storage"><SlidersHorizontal/>Filters</Link></div></section></div>
 <section className="glassPanel trayPanel"><div className="panelHead compact"><div><span className="eyebrowText">CURRENT WT</span><h2>Lens overview</h2><p>Click a lens to hold it in the inspection viewer</p></div><span className="trayCount">WT {sample?.wt_index||1} · {wtSamples.length}/16</span></div><div className="trayStrip">{Array.from({length:16},(_,i)=>{const s=wtSamples.find(x=>x.position===i+1);if(!s)return <div key={i} className="trayCard placeholder"><span>{i+1}</span></div>;const r=resultMap.get(s.id),ch=Object.keys(s.images)[0];return <button className={`trayCard ${s.id===current?'selected':''}`} key={s.id} onClick={()=>select(s.id)}><span className="posBadge">{s.position}</span><img src={previewUrl(datasetId,s.id,ch)} alt="lens"/><div><small>{s.metadata.code||`Position ${s.position}`}</small><b className={(r?.status||'idle').toLowerCase()}>{r?.status||'WAIT'}</b></div></button>})}</div></section>
 <section className="lowerWorkspace glassPanel"><div className="workspaceTabs"><button className={bottomTab==='wt'?'active':''} onClick={()=>setBottomTab('wt')}>WT View</button><button className={bottomTab==='yield'?'active':''} onClick={()=>setBottomTab('yield')}>Yield & Trend</button><button className={bottomTab==='messages'?'active':''} onClick={()=>setBottomTab('messages')}>System Messages</button><div className="jobState">{job?`${job.completed}/${job.total} · ${job.status}`:'Ready'}</div></div>{bottomTab==='wt'&&<div className="wtWorkspace"><div className="wtSummary"><Kpi label="OK" value={String(wtSamples.filter(s=>resultMap.get(s.id)?.status==='OK').length)} tone="good"/><Kpi label="NOK" value={String(wtSamples.filter(s=>resultMap.get(s.id)?.status==='NOK').length)} tone="bad"/><Kpi label="Not inspected" value={String(wtSamples.filter(s=>!resultMap.has(s.id)).length)}/></div><div className="quickActions"><button className="primaryAction" onClick={run} disabled={busy||!datasetId}>{busy?<Loader2 className="spin"/>:<Play/>}Run folder</button><button onClick={()=>job&&api.cancel(job.id)}><Square/>Stop</button><button><Pause/>Pause display</button><a href={datasetId?archiveUrl(datasetId):'#'}><Archive/>Archive dataset</a></div>{job&&<div className="jobProgress"><i style={{width:`${job.total?job.completed/job.total*100:0}%`}}/></div>}</div>}{bottomTab==='yield'&&<div className="yieldWorkspace"><TrendChart results={results}/><div className="yieldCards"><Kpi label="Yield" value={`${yieldPct.toFixed(2)}%`} tone="good"/><Kpi label="NOK rate" value={`${results.length?(counts.NOK/results.length*100).toFixed(2):'0.00'}%`} tone="bad"/><Kpi label="Total evaluated" value={String(results.length)}/></div></div>}{bottomTab==='messages'&&<div className="messageList">{logs.slice(0,60).map((l,i)=><div key={i}><time>{new Date(l.time).toLocaleTimeString()}</time><i className={l.level}/><span>{l.message}</span></div>)}</div>}</section>
 {toast&&<button className="toast" onClick={()=>setToast('')}><TriangleAlert/>{toast}</button>}<DatasetLoader open={loader} onClose={()=>setLoader(false)} onLoaded={id=>refreshDatasets(id)}/></>}
function Kpi({label,value,tone=''}:{label:string;value:string;tone?:string}){return <div className={`kpiCard ${tone}`}><small>{label}</small><b>{value}</b></div>}
function Meta({label,value}:{label:string;value?:string|number|null}){return <label><small>{label}</small><b title={String(value||'—')}>{value||'—'}</b></label>}
