'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Crosshair,Focus,Maximize2,Minus,MousePointer2,Plus,RotateCcw,ScanSearch} from 'lucide-react';
import type {Defect} from '@/types';

type Props={imageUrl:string;defects:Defect[];selectedDefect?:number;showDefects?:boolean;showCrosshair?:boolean;onProbe?:(p:{x:number;y:number;gray:number|null})=>void};
export function InspectionCanvas({imageUrl,defects,selectedDefect=0,showDefects=true,showCrosshair=true,onProbe}:Props){
 const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),off=useRef<HTMLCanvasElement|null>(null),img=useRef<HTMLImageElement|null>(null);
 const [view,setView]=useState({scale:1,x:0,y:0}); const [drag,setDrag]=useState<{x:number;y:number;vx:number;vy:number}|null>(null); const [loaded,setLoaded]=useState(false); const [probe,setProbe]=useState<{x:number;y:number;gray:number|null}|null>(null);
 const fit=useCallback(()=>{const h=host.current,i=img.current;if(!h||!i||!i.naturalWidth)return;const r=h.getBoundingClientRect();const s=Math.min((r.width-50)/i.naturalWidth,(r.height-50)/i.naturalHeight);setView({scale:s,x:(r.width-i.naturalWidth*s)/2,y:(r.height-i.naturalHeight*s)/2})},[]);
 useEffect(()=>{setLoaded(false);setProbe(null);if(!imageUrl){img.current=null;return}const i=new Image();i.crossOrigin='anonymous';i.onload=()=>{img.current=i;const o=document.createElement('canvas');o.width=i.naturalWidth;o.height=i.naturalHeight;const c=o.getContext('2d',{willReadFrequently:true});c?.drawImage(i,0,0);off.current=o;setLoaded(true);requestAnimationFrame(fit)};i.src=imageUrl;return()=>{i.onload=null}},[imageUrl,fit]);
 const draw=useCallback(()=>{const c=canvas.current,h=host.current,i=img.current;if(!c||!h)return;const r=h.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);if(c.width!==Math.floor(r.width*dpr)||c.height!==Math.floor(r.height*dpr)){c.width=Math.floor(r.width*dpr);c.height=Math.floor(r.height*dpr);c.style.width=`${r.width}px`;c.style.height=`${r.height}px`}const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const g=ctx.createRadialGradient(r.width*.5,r.height*.45,20,r.width*.5,r.height*.5,Math.max(r.width,r.height));g.addColorStop(0,'#0c1622');g.addColorStop(1,'#02070d');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);if(!i||!loaded){ctx.fillStyle='#7c93a8';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText(imageUrl?'Loading image…':'Select a lens image',r.width/2,r.height/2);return}ctx.imageSmoothingEnabled=true;ctx.drawImage(i,view.x,view.y,i.naturalWidth*view.scale,i.naturalHeight*view.scale);if(showDefects){defects.forEach((d,index)=>{if(!d.bbox_xywh_norm)return;const [x,y,w,hb]=d.bbox_xywh_norm;const rx=view.x+x*i.naturalWidth*view.scale,ry=view.y+y*i.naturalHeight*view.scale,rw=w*i.naturalWidth*view.scale,rh=hb*i.naturalHeight*view.scale;const selected=index===selectedDefect;const color=d.severity==='critical'?'#ff3856':d.severity==='major'?'#ff4f6d':'#ffb62e';ctx.save();ctx.strokeStyle=color;ctx.lineWidth=selected?3:2;ctx.setLineDash(selected?[]:[7,5]);ctx.shadowColor=color;ctx.shadowBlur=selected?12:3;ctx.strokeRect(rx,ry,rw,rh);ctx.fillStyle=color;ctx.font='600 11px system-ui';ctx.fillText(d.name,rx+3,Math.max(13,ry-6));ctx.restore()})}if(showCrosshair){const cx=view.x+i.naturalWidth*view.scale/2,cy=view.y+i.naturalHeight*view.scale/2;ctx.save();ctx.strokeStyle='rgba(68,181,255,.85)';ctx.lineWidth=1;ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(cx-70,cy);ctx.lineTo(cx+70,cy);ctx.moveTo(cx,cy-70);ctx.lineTo(cx,cy+70);ctx.stroke();ctx.restore()}},[defects,imageUrl,loaded,selectedDefect,showCrosshair,showDefects,view]);
 useEffect(()=>{draw()},[draw]);useEffect(()=>{const ro=new ResizeObserver(()=>draw());if(host.current)ro.observe(host.current);return()=>ro.disconnect()},[draw]);
 function zoomAt(f:number,cx?:number,cy?:number){const h=host.current;if(!h||!img.current)return;const rect=h.getBoundingClientRect(),px=cx??rect.width/2,py=cy??rect.height/2;setView(v=>{const ns=Math.max(.05,Math.min(8,v.scale*f));const ix=(px-v.x)/v.scale,iy=(py-v.y)/v.scale;return{scale:ns,x:px-ix*ns,y:py-iy*ns}})}
 function wheel(e:React.WheelEvent){e.preventDefault();const rect=(e.currentTarget as HTMLElement).getBoundingClientRect();zoomAt(e.deltaY<0?1.12:.89,e.clientX-rect.left,e.clientY-rect.top)}
 function pointerDown(e:React.PointerEvent){(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setDrag({x:e.clientX,y:e.clientY,vx:view.x,vy:view.y})}
 function pointerMove(e:React.PointerEvent){const h=host.current,i=img.current;if(drag)setView(v=>({...v,x:drag.vx+e.clientX-drag.x,y:drag.vy+e.clientY-drag.y}));if(!h||!i||!off.current)return;const r=h.getBoundingClientRect(),cx=e.clientX-r.left,cy=e.clientY-r.top,ix=Math.floor((cx-view.x)/view.scale),iy=Math.floor((cy-view.y)/view.scale);if(ix<0||iy<0||ix>=i.naturalWidth||iy>=i.naturalHeight){setProbe(null);return}let gray:number|null=null;try{const d=off.current.getContext('2d',{willReadFrequently:true})?.getImageData(ix,iy,1,1).data;if(d)gray=Math.round((d[0]+d[1]+d[2])/3)}catch{}const p={x:ix,y:iy,gray};setProbe(p);onProbe?.(p)}
 function focusDefect(){const i=img.current,h=host.current,d=defects[selectedDefect];if(!i||!h||!d?.bbox_xywh_norm)return;const [x,y,w,hh]=d.bbox_xywh_norm,r=h.getBoundingClientRect();const targetW=Math.max(w*i.naturalWidth,50),targetH=Math.max(hh*i.naturalHeight,50),s=Math.min(r.width*.55/targetW,r.height*.55/targetH,6);const cx=(x+w/2)*i.naturalWidth,cy=(y+hh/2)*i.naturalHeight;setView({scale:s,x:r.width/2-cx*s,y:r.height/2-cy*s})}
 return <div className="canvasHost" ref={host} onWheel={wheel} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)}><canvas ref={canvas}/><div className="canvasTools" onPointerDown={e=>e.stopPropagation()}><button onClick={()=>zoomAt(1.2)} title="Zoom in"><Plus/></button><button onClick={()=>zoomAt(.83)} title="Zoom out"><Minus/></button><button onClick={fit} title="Fit image"><RotateCcw/></button><button onClick={()=>{if(!img.current||!host.current)return;const r=host.current.getBoundingClientRect();setView({scale:1,x:(r.width-img.current.naturalWidth)/2,y:(r.height-img.current.naturalHeight)/2})}} title="1:1"><ScanSearch/></button><button onClick={focusDefect} title="Focus selected defect"><Focus/></button><button onClick={()=>host.current?.requestFullscreen?.()} title="Fullscreen"><Maximize2/></button></div>{probe&&<div className="pixelProbe"><MousePointer2/><b>X {probe.x}</b><b>Y {probe.y}</b><b>Gray {probe.gray??'—'}</b></div>}<div className="canvasHint"><Crosshair/> drag to pan · wheel to zoom</div></div>
}
